export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED= 'ORDER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'